services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=0.0.1
    ports:
      - "80:80"  # Bitnami nginx usa puerto 8080 por defecto
    environment:
      - NODE_ENV=production
    restart: always
    container_name: react-static-app
    
    volumes:
      - node_modules:/app/node_modules
    # Opcional: Configuración de health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

    
volumes:
  node_modules:
  # Volumen para persistir node_modules

    # Configuración de usuario para Bitnami (seguridad)
    #user: "1001:1001"